/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliesRouteImport } from './routes/supplies'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RadiologyRouteImport } from './routes/radiology'
import { Route as PricelistRouteImport } from './routes/pricelist'
import { Route as PhilhealthRouteImport } from './routes/philhealth'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as OpdRouteImport } from './routes/opd'
import { Route as MiscellaneousRouteImport } from './routes/miscellaneous'
import { Route as MedicalRecordsRouteImport } from './routes/medical-records'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ErRouteImport } from './routes/er'
import { Route as EclaimsMonitoringRouteImport } from './routes/eclaims-monitoring'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as CaseratesRouteImport } from './routes/caserates'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EclaimsMonitoringBatchTransmitRouteImport } from './routes/eclaims-monitoring_.batch-transmit'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as ApiCaseRatesIndexRouteImport } from './routes/api/case-rates/index'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiSyncSaveRouteImport } from './routes/api/sync/save'
import { Route as ApiSyncLoadRouteImport } from './routes/api/sync/load'
import { Route as ApiHealthDbRouteImport } from './routes/api/health/db'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const SuppliesRoute = SuppliesRouteImport.update({
  id: '/supplies',
  path: '/supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiologyRoute = RadiologyRouteImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => rootRouteImport,
} as any)
const PricelistRoute = PricelistRouteImport.update({
  id: '/pricelist',
  path: '/pricelist',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilhealthRoute = PhilhealthRouteImport.update({
  id: '/philhealth',
  path: '/philhealth',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const OpdRoute = OpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => rootRouteImport,
} as any)
const MiscellaneousRoute = MiscellaneousRouteImport.update({
  id: '/miscellaneous',
  path: '/miscellaneous',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRecordsRoute = MedicalRecordsRouteImport.update({
  id: '/medical-records',
  path: '/medical-records',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ErRoute = ErRouteImport.update({
  id: '/er',
  path: '/er',
  getParentRoute: () => rootRouteImport,
} as any)
const EclaimsMonitoringRoute = EclaimsMonitoringRouteImport.update({
  id: '/eclaims-monitoring',
  path: '/eclaims-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseratesRoute = CaseratesRouteImport.update({
  id: '/caserates',
  path: '/caserates',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EclaimsMonitoringBatchTransmitRoute =
  EclaimsMonitoringBatchTransmitRouteImport.update({
    id: '/eclaims-monitoring_/batch-transmit',
    path: '/eclaims-monitoring/batch-transmit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaseRatesIndexRoute = ApiCaseRatesIndexRouteImport.update({
  id: '/api/case-rates/',
  path: '/api/case-rates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/api/users/$id',
  path: '/api/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncSaveRoute = ApiSyncSaveRouteImport.update({
  id: '/api/sync/save',
  path: '/api/sync/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncLoadRoute = ApiSyncLoadRouteImport.update({
  id: '/api/sync/load',
  path: '/api/sync/load',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthDbRoute = ApiHealthDbRouteImport.update({
  id: '/api/health/db',
  path: '/api/health/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/caserates': typeof CaseratesRoute
  '/cashier': typeof CashierRoute
  '/consultations': typeof ConsultationsRoute
  '/dashboard': typeof DashboardRoute
  '/eclaims-monitoring': typeof EclaimsMonitoringRoute
  '/er': typeof ErRoute
  '/inventory': typeof InventoryRoute
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/medical-records': typeof MedicalRecordsRoute
  '/miscellaneous': typeof MiscellaneousRoute
  '/opd': typeof OpdRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/philhealth': typeof PhilhealthRoute
  '/pricelist': typeof PricelistRoute
  '/radiology': typeof RadiologyRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/supplies': typeof SuppliesRoute
  '/eclaims-monitoring/batch-transmit': typeof EclaimsMonitoringBatchTransmitRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/sync/load': typeof ApiSyncLoadRoute
  '/api/sync/save': typeof ApiSyncSaveRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/case-rates/': typeof ApiCaseRatesIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/caserates': typeof CaseratesRoute
  '/cashier': typeof CashierRoute
  '/consultations': typeof ConsultationsRoute
  '/dashboard': typeof DashboardRoute
  '/eclaims-monitoring': typeof EclaimsMonitoringRoute
  '/er': typeof ErRoute
  '/inventory': typeof InventoryRoute
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/medical-records': typeof MedicalRecordsRoute
  '/miscellaneous': typeof MiscellaneousRoute
  '/opd': typeof OpdRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/philhealth': typeof PhilhealthRoute
  '/pricelist': typeof PricelistRoute
  '/radiology': typeof RadiologyRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/supplies': typeof SuppliesRoute
  '/eclaims-monitoring/batch-transmit': typeof EclaimsMonitoringBatchTransmitRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/sync/load': typeof ApiSyncLoadRoute
  '/api/sync/save': typeof ApiSyncSaveRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/case-rates': typeof ApiCaseRatesIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admission': typeof AdmissionRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/caserates': typeof CaseratesRoute
  '/cashier': typeof CashierRoute
  '/consultations': typeof ConsultationsRoute
  '/dashboard': typeof DashboardRoute
  '/eclaims-monitoring': typeof EclaimsMonitoringRoute
  '/er': typeof ErRoute
  '/inventory': typeof InventoryRoute
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/medical-records': typeof MedicalRecordsRoute
  '/miscellaneous': typeof MiscellaneousRoute
  '/opd': typeof OpdRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/philhealth': typeof PhilhealthRoute
  '/pricelist': typeof PricelistRoute
  '/radiology': typeof RadiologyRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/supplies': typeof SuppliesRoute
  '/eclaims-monitoring_/batch-transmit': typeof EclaimsMonitoringBatchTransmitRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/sync/load': typeof ApiSyncLoadRoute
  '/api/sync/save': typeof ApiSyncSaveRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/case-rates/': typeof ApiCaseRatesIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admission'
    | '/appointments'
    | '/billing'
    | '/caserates'
    | '/cashier'
    | '/consultations'
    | '/dashboard'
    | '/eclaims-monitoring'
    | '/er'
    | '/inventory'
    | '/laboratory'
    | '/login'
    | '/medical-records'
    | '/miscellaneous'
    | '/opd'
    | '/patients'
    | '/pharmacy'
    | '/philhealth'
    | '/pricelist'
    | '/radiology'
    | '/register'
    | '/reports'
    | '/settings'
    | '/supplies'
    | '/eclaims-monitoring/batch-transmit'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/health/db'
    | '/api/sync/load'
    | '/api/sync/save'
    | '/api/users/$id'
    | '/api/case-rates/'
    | '/api/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admission'
    | '/appointments'
    | '/billing'
    | '/caserates'
    | '/cashier'
    | '/consultations'
    | '/dashboard'
    | '/eclaims-monitoring'
    | '/er'
    | '/inventory'
    | '/laboratory'
    | '/login'
    | '/medical-records'
    | '/miscellaneous'
    | '/opd'
    | '/patients'
    | '/pharmacy'
    | '/philhealth'
    | '/pricelist'
    | '/radiology'
    | '/register'
    | '/reports'
    | '/settings'
    | '/supplies'
    | '/eclaims-monitoring/batch-transmit'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/health/db'
    | '/api/sync/load'
    | '/api/sync/save'
    | '/api/users/$id'
    | '/api/case-rates'
    | '/api/users'
  id:
    | '__root__'
    | '/'
    | '/admission'
    | '/appointments'
    | '/billing'
    | '/caserates'
    | '/cashier'
    | '/consultations'
    | '/dashboard'
    | '/eclaims-monitoring'
    | '/er'
    | '/inventory'
    | '/laboratory'
    | '/login'
    | '/medical-records'
    | '/miscellaneous'
    | '/opd'
    | '/patients'
    | '/pharmacy'
    | '/philhealth'
    | '/pricelist'
    | '/radiology'
    | '/register'
    | '/reports'
    | '/settings'
    | '/supplies'
    | '/eclaims-monitoring_/batch-transmit'
    | '/api/auth/login'
    | '/api/auth/register'
    | '/api/health/db'
    | '/api/sync/load'
    | '/api/sync/save'
    | '/api/users/$id'
    | '/api/case-rates/'
    | '/api/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionRoute: typeof AdmissionRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BillingRoute: typeof BillingRoute
  CaseratesRoute: typeof CaseratesRoute
  CashierRoute: typeof CashierRoute
  ConsultationsRoute: typeof ConsultationsRoute
  DashboardRoute: typeof DashboardRoute
  EclaimsMonitoringRoute: typeof EclaimsMonitoringRoute
  ErRoute: typeof ErRoute
  InventoryRoute: typeof InventoryRoute
  LaboratoryRoute: typeof LaboratoryRoute
  LoginRoute: typeof LoginRoute
  MedicalRecordsRoute: typeof MedicalRecordsRoute
  MiscellaneousRoute: typeof MiscellaneousRoute
  OpdRoute: typeof OpdRoute
  PatientsRoute: typeof PatientsRoute
  PharmacyRoute: typeof PharmacyRoute
  PhilhealthRoute: typeof PhilhealthRoute
  PricelistRoute: typeof PricelistRoute
  RadiologyRoute: typeof RadiologyRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SuppliesRoute: typeof SuppliesRoute
  EclaimsMonitoringBatchTransmitRoute: typeof EclaimsMonitoringBatchTransmitRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiHealthDbRoute: typeof ApiHealthDbRoute
  ApiSyncLoadRoute: typeof ApiSyncLoadRoute
  ApiSyncSaveRoute: typeof ApiSyncSaveRoute
  ApiUsersIdRoute: typeof ApiUsersIdRoute
  ApiCaseRatesIndexRoute: typeof ApiCaseRatesIndexRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supplies': {
      id: '/supplies'
      path: '/supplies'
      fullPath: '/supplies'
      preLoaderRoute: typeof SuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radiology': {
      id: '/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof RadiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricelist': {
      id: '/pricelist'
      path: '/pricelist'
      fullPath: '/pricelist'
      preLoaderRoute: typeof PricelistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philhealth': {
      id: '/philhealth'
      path: '/philhealth'
      fullPath: '/philhealth'
      preLoaderRoute: typeof PhilhealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opd': {
      id: '/opd'
      path: '/opd'
      fullPath: '/opd'
      preLoaderRoute: typeof OpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miscellaneous': {
      id: '/miscellaneous'
      path: '/miscellaneous'
      fullPath: '/miscellaneous'
      preLoaderRoute: typeof MiscellaneousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-records': {
      id: '/medical-records'
      path: '/medical-records'
      fullPath: '/medical-records'
      preLoaderRoute: typeof MedicalRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/er': {
      id: '/er'
      path: '/er'
      fullPath: '/er'
      preLoaderRoute: typeof ErRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eclaims-monitoring': {
      id: '/eclaims-monitoring'
      path: '/eclaims-monitoring'
      fullPath: '/eclaims-monitoring'
      preLoaderRoute: typeof EclaimsMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caserates': {
      id: '/caserates'
      path: '/caserates'
      fullPath: '/caserates'
      preLoaderRoute: typeof CaseratesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eclaims-monitoring_/batch-transmit': {
      id: '/eclaims-monitoring_/batch-transmit'
      path: '/eclaims-monitoring/batch-transmit'
      fullPath: '/eclaims-monitoring/batch-transmit'
      preLoaderRoute: typeof EclaimsMonitoringBatchTransmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users/'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/case-rates/': {
      id: '/api/case-rates/'
      path: '/api/case-rates'
      fullPath: '/api/case-rates/'
      preLoaderRoute: typeof ApiCaseRatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/api/users/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/save': {
      id: '/api/sync/save'
      path: '/api/sync/save'
      fullPath: '/api/sync/save'
      preLoaderRoute: typeof ApiSyncSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/load': {
      id: '/api/sync/load'
      path: '/api/sync/load'
      fullPath: '/api/sync/load'
      preLoaderRoute: typeof ApiSyncLoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/db': {
      id: '/api/health/db'
      path: '/api/health/db'
      fullPath: '/api/health/db'
      preLoaderRoute: typeof ApiHealthDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionRoute: AdmissionRoute,
  AppointmentsRoute: AppointmentsRoute,
  BillingRoute: BillingRoute,
  CaseratesRoute: CaseratesRoute,
  CashierRoute: CashierRoute,
  ConsultationsRoute: ConsultationsRoute,
  DashboardRoute: DashboardRoute,
  EclaimsMonitoringRoute: EclaimsMonitoringRoute,
  ErRoute: ErRoute,
  InventoryRoute: InventoryRoute,
  LaboratoryRoute: LaboratoryRoute,
  LoginRoute: LoginRoute,
  MedicalRecordsRoute: MedicalRecordsRoute,
  MiscellaneousRoute: MiscellaneousRoute,
  OpdRoute: OpdRoute,
  PatientsRoute: PatientsRoute,
  PharmacyRoute: PharmacyRoute,
  PhilhealthRoute: PhilhealthRoute,
  PricelistRoute: PricelistRoute,
  RadiologyRoute: RadiologyRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SuppliesRoute: SuppliesRoute,
  EclaimsMonitoringBatchTransmitRoute: EclaimsMonitoringBatchTransmitRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiHealthDbRoute: ApiHealthDbRoute,
  ApiSyncLoadRoute: ApiSyncLoadRoute,
  ApiSyncSaveRoute: ApiSyncSaveRoute,
  ApiUsersIdRoute: ApiUsersIdRoute,
  ApiCaseRatesIndexRoute: ApiCaseRatesIndexRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
